<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>L2TP</key>
	<dict>
		<key>SystemConfig</key>
		<dict>
			<key>IPSec</key>
			<dict>
				<key>AuthenticationMethod</key>
				<string>SharedSecret</string>
				<key>ExportedSharedSecret</key>
				<data>
				${vpn_ipsec_psk_encrypted}
				</data>
				<key>SharedSecret</key>
				<string>E60E9734-7BDD-4DC3-96C5-1D2AAC49752F.SS</string>
				<key>SharedSecretEncryption</key>
				<string>Keychain</string>
			</dict>
			<key>PPP</key>
			<dict>
				<key>ACSPEnabled</key>
				<integer>1</integer>
				<key>AuthName</key>
				<string>${vpn_username}</string>
				<key>AuthPassword</key>
				<string>E60E9734-7BDD-4DC3-96C5-1D2AAC49752F</string>
				<key>AuthPasswordEncryption</key>
				<string>Keychain</string>
				<key>CommDisplayTerminalWindow</key>
				<integer>0</integer>
				<key>CommRedialCount</key>
				<integer>1</integer>
				<key>CommRedialEnabled</key>
				<integer>0</integer>
				<key>CommRedialInterval</key>
				<integer>5</integer>
				<key>CommRemoteAddress</key>
				<string>${ip_address}</string>
				<key>CommUseTerminalScript</key>
				<integer>0</integer>
				<key>DialOnDemand</key>
				<integer>0</integer>
				<key>DisconnectOnFastUserSwitch</key>
				<integer>1</integer>
				<key>DisconnectOnIdle</key>
				<integer>0</integer>
				<key>DisconnectOnIdleTimer</key>
				<integer>600</integer>
				<key>DisconnectOnLogout</key>
				<integer>1</integer>
				<key>DisconnectOnSleep</key>
				<integer>0</integer>
				<key>ExportedPassword</key>
				<data>
				${vpn_password_encrypted}
				</data>
				<key>IPCPCompressionVJ</key>
				<integer>0</integer>
				<key>IdleReminder</key>
				<integer>0</integer>
				<key>IdleReminderTimer</key>
				<integer>1800</integer>
				<key>LCPEchoEnabled</key>
				<integer>1</integer>
				<key>LCPEchoFailure</key>
				<integer>15</integer>
				<key>LCPEchoInterval</key>
				<integer>20</integer>
				<key>Logfile</key>
				<string>/var/log/ppp.log</string>
				<key>VerboseLogging</key>
				<integer>0</integer>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
